Transform: AWS::Serverless-2016-10-31
Parameters:
  CertificateArn:
    Type: String
  HostedZoneId:
    Type: String
  Domain:
    Type: String
  ArtifactsBucketName:
    Type: String
  CloudFormationRole:
    Type: String
Resources:
  Frontend:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.us-east-1.amazonaws.com/learning-ci-artifacts/staging/infrastructure/current/12c5879aef839ff58567bdf0eeb08cf3.template
      Parameters:
        DomainName:
          Fn::Sub: app.${Domain}
        HostedZoneId:
          Ref: HostedZoneId
        CertificateArn:
          Ref: CertificateArn
  CodePipelines:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.us-east-1.amazonaws.com/learning-ci-artifacts/staging/infrastructure/current/64c128274e42972b1b9032412fd0c9f7.template
      Parameters:
        FrontendDistributionId:
          Fn::GetAtt:
          - Frontend
          - Outputs.CloudFrontDistributionId
        FrontendBucketName:
          Fn::GetAtt:
          - Frontend
          - Outputs.FrontendBucketName
        ArtifactsBucketName:
          Ref: ArtifactsBucketName
        CloudFormationRole:
          Ref: CloudFormationRole
